config/routes.rb
Accessny::Application.routes.draw do
  resources :validations

end

app/models/validation.rb
require 'securerandom'
class Validation < ActiveRecord::Base
  attr_accessible :encoded_id, :tag_id
  def self.add_tag(parameters)
  	return Validation.new(:encoded_id => Validation.generate_hash8(parameters[:tag_id])	)
  end
  def self.generate_hash8(tag_id)
  	generated = SecureRandom.hex(4)
  	if (Validation.find_by_encoded_id(generated) == nil)
  		return generated
	else
		Validation.generate_hash8(tag_id)
	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
  # GET /validations
  # GET /validations.json
  def index
    @validations = Validation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @validations }
    end
  end

  # GET /validations/1
  # GET /validations/1.json
  def show
    #debugger
    @validation = Validation.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @validation }
    end
  end

  # GET /validations/new
  # GET /validations/new.json
  def new
    @validation = Validation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @validation }
    end
  end

  # GET /validations/1/edit
  def edit
    @validation = Validation.find(params[:id])
  end

  # POST /validations
  # POST /validations.json
  def create
    #@validation = Validation.new(params[:validation])
    #debugger
    @validation = Validation.add_tag(params[:validation])
    respond_to do |format|
      if @validation.save
        format.html { redirect_to @validation, notice: 'Validation was successfully created.' }
        format.json { render json: @validation, status: :created, location: @validation }
      else
        format.html { render action: "new" }
        format.json { render json: @validation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /validations/1
  # PUT /validations/1.json
  def update
    @validation = Validation.find(params[:id])

    respond_to do |format|
      if @validation.update_attributes(params[:validation])
        format.html { redirect_to @validation, notice: 'Validation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @validation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /validations/1
  # DELETE /validations/1.json
  def destroy
    @validation = Validation.find(params[:id])
    @validation.destroy

    respond_to do |format|
      format.html { redirect_to validations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/validations_helper.rb
module ValidationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accessny</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/validations/_form.html.erb
<%= form_for(@validation) do |f| %>
  <% if @validation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@validation.errors.count, "error") %> prohibited this validation from being saved:</h2>

      <ul>
      <% @validation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :encoded_id %><br />
    <%= f.text_field :encoded_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/validations/edit.html.erb
<h1>Editing validation</h1>

<%= render 'form' %>

<%= link_to 'Show', @validation %> |
<%= link_to 'Back', validations_path %>

app/views/validations/index.html.erb
<h1>Listing validations</h1>

<table>
  <tr>
    <th>Encoded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @validations.each do |validation| %>
  <tr>
    <td><%= validation.encoded_id %></td>
    <td><%= link_to 'Show', validation %></td>
    <td><%= link_to 'Edit', edit_validation_path(validation) %></td>
    <td><%= link_to 'Destroy', validation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Validation', new_validation_path %>

app/views/validations/new.html.erb
<h1>New validation</h1>

<%= render 'form' %>

<%= link_to 'Back', validations_path %>

app/views/validations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Encoded:</b>
  <%= @validation.encoded_id %>
</p>


<%= link_to 'Edit', edit_validation_path(@validation) %> |
<%= link_to 'Back', validations_path %>